mysite/urls.py
from django.contrib import admin
from django.urls import path, include


app_name = 'tutorial'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tutorial.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('users/', include('users.urls'))
]

tutorial/urls.py
from django.urls import path, reverse
from . import views


app_name = 'tutorial'
urlpatterns = [
    path('', views.home_page, name='home'),
    path('<cat_slug>/', views.series_view, name='single_slug'),
    path('<cat_slug>/<series_slug>/', views.tutorial_view, name='sub_sub_cat'),
    path('<cat_slug>/<series_slug>/<tutorial_slug>/', views.tutorial_details_view, name='tutorial_detail')
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('signin/', views.signin_request, name='signin'),
    path('logout/', views.logout_request, name='logout'),
]

tutorial/models.py
from django.db import models
from datetime import datetime
from django.utils.text import slugify
from tinymce.widgets import TinyMCE
from django.db import models


class TutorialCategory(models.Model):
    category_title = models.CharField(max_length=150)
    category_summary = models.CharField(max_length=150)
    category_slug = models.SlugField(default=1, blank=True)

    def __str__(self):
        return self.category_title

    def save(self, *args, **kwargs):
        self.category_slug = slugify(self.category_title)
        super(TutorialCategory, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'


class TutorialSeries(models.Model):
    series_title = models.CharField(max_length=200)
    series_maincategory = models.ForeignKey(TutorialCategory, default=1, on_delete=models.SET_DEFAULT)
    series_summary = models.CharField(max_length=200)
    series_slug = models.SlugField(default=1, blank=True)

    def __str__(self):
        return self.series_title

    class Meta:
        verbose_name_plural = 'Series'


class Tutorial(models.Model):
    tutorial_title = models.CharField(max_length=150)
    tutorial_content = models.TextField()
    tutorial_published = models.DateTimeField("date Published", default=datetime.now())
    tutorial_series = models.ForeignKey(TutorialSeries, default=1, on_delete=models.SET_DEFAULT, related_name='tutorials')
    tutorial_slug = models.SlugField(default=1, blank=True)

    def snippet(self):
        return self.tutorial_content[:200] + '...'

    def __str__(self):
        return self.tutorial_title

    def save(self, *args, **kwargs):
        self.tutorial_slug = slugify(self.tutorial_title)
        super(Tutorial, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Tutorials'


class Section(models.Model):
    section_title = models.CharField(max_length=150)
    section_content = models.TextField()
    section_published = models.DateTimeField("date Published", default=datetime.now())
    section_tutorial = models.ForeignKey(Tutorial, default=1, on_delete=models.SET_DEFAULT)
    section_slug = models.SlugField(default=1, blank=True)

    def snippet(self):
        return self.section_content[:200] + '...'

    def __str__(self):
        return self.section_title

    def save(self, *args, **kwargs):
        self.section_slug = slugify(self.section_title)
        super(Section, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Sections'

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

tutorial/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Tutorial, TutorialCategory, TutorialSeries, Section
from django.contrib.auth.forms import UserCreationForm


def series_view(request, cat_slug):
    matching_series = TutorialSeries.objects.filter(series_maincategory__category_slug=cat_slug)  

    return render(request, 'tutorial/sub-category.html', context={
        "matching_series": matching_series,
    })


def tutorial_view(request, cat_slug, series_slug):
    matching_series = Tutorial.objects.filter(tutorial_series__series_slug=series_slug)  

    return render(request, 'tutorial/sub-sub-category.html', context={
        "matching_series": matching_series,
    })


def tutorial_details_view(request, cat_slug, series_slug, tutorial_slug):

    object = get_object_or_404(Tutorial, tutorial_slug=tutorial_slug)
    return render(request, 'tutorial/tutorial-detail.html', context={
        'obj': object
    })


def home_page(request):
    return render(request=request, template_name='tutorial/home.html', context={'tutorials': TutorialCategory.objects.all()})


def tutorial_detail(request, id):
    return render(request, template_name='tutorial/tutorial_detail.html', context={'obj': Tutorial.objects.get(id=id)})

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from .forms import UserRegistrationForm
# Create your views here.


def logout_request(request):
    logout(request)
    return redirect('users:signin')


def signup(request):
    form = UserRegistrationForm(request.POST or None)
    if form.is_valid():
        form.save()
        user = form.cleaned_data.get('username')
        messages.success(
            request, f'Account has been created successfully for {user}')
        return redirect('users:signin')
    return render(request, 'users/signup.html', context={
        'form': form
    })


def signin_request(request):
    if request.method == 'POST':
        forms = AuthenticationForm(request, request.POST)
        if forms.is_valid():
            username = forms.cleaned_data.get('username')
            password = forms.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(
                    request, f'You have been successfully logged in as {username}')
                return redirect('tutorial:home')
            else:
                messages.error(
                    request, 'There was an error in your password and email!')
    else:
        forms = AuthenticationForm()
    return render(request, 'users/signin.html', context={
        'form': forms
    })

tutorial/templates/tutorial/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% block style %}
    {% endblock style %}

    <title>Hello, world!</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'tutorial:home' %}">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'tutorial:home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <div class="d-flex pr-3" style="position:absolute; right:0;">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link btn btn-outline-success" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:signin' %}">Sign In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:signup' %}">Sign Up</a>
                    </li>
                    {% endif %}
                </div>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
            </ul>
            <!-- <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form> -->
        </div>
    </nav>
    <div class="container p-3">
        {% block content %}

        {% endblock content %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

    <script src="{% static 'tinymce/js/prism.js' %}"></script>
    <script src="{% static 'js/myscript.js' %}"></script>
</body>

</html>

tutorial/templates/tutorial/home.html
{% extends 'tutorial/base.html' %}

{% block style %}
<style>
    .card:hover {
        cursor: pointer;
        box-shadow: 0 0 7px #f3f3f3;
    }
    .card-link:hover{
        text-decoration: underline;
        color: #f3f3f3;
    }
</style>
{% endblock style %}

{% block content %}
<div class="collection">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    <div class="d-flex flex-wrap">

        {% for tutorial in tutorials %}
        <div class="card col-lg-3 col-md-4 col-sm-12 m-4" style="width: 18rem;">
            <div class="card-body">
                
                <a class='card-link' href="{% url 'tutorial:single_slug' tutorial.category_slug %}">
                    <h5 class="card-title bg-success p-4 text-white" style="border-radius: 8px;">{{ tutorial.category_title }}</h5>
                </a>
                <hr>
                {% for tut in tutorial.tutorialseries_set.all %}
                    <div class="p-2 mb-1 text-white" style="border-radius: 5px;background-color: dodgerblue;">{{ tut.series_title }}</div>
                        {% for subtut in tut.tutorials.all %}  # related_name =  'tutorials'
                            <div class="p-1 text-white ml-3 w-85 mb-1" style="border-radius: 4px; background-color: darkgoldenrod;">
                                {{ subtut.tutorial_title }}
                            </div>
                        {% endfor %}
                {% endfor %}
            </div>
        </div>
        {% endfor %}
    </div>

    {% endblock content %}

tutorial/templates/tutorial/original.html
{% extends 'tutorial/base.html' %}

{% block style %}
<style>
    .card:hover {
        cursor: pointer;
        box-shadow: 0 0 7px #f3f3f3;
    }
</style>
{% endblock style %}

{% block content %}
<div class="collection">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}

    {% for sub_cat in matching_series %}
    {% for sub_sub_cat in sub_cat.tutorial_set.all %}
    {{ sub_sub_cat.tutorial_title }}
    {% endfor %}
    {% endfor %}

    <div class="d-flex flex-wrap">
        {% for tut, partone in part_ones.items %}

        <div class="col s12 m6 l4">
            <a href="{{partone}}" , style="color:#000">
                <div class="card hoverable">
                    <div class="card-content">
                        <div class="card-title">{{tut.tutorial_series}}</div>
                        <!--<p style="font-size:70%">Published {{tut.tutorial_published}}</p>-->
                        <p>{{tut.series_summary}}</p>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>

    {% endblock content %}

tutorial/templates/tutorial/sub-category.html
{% extends 'tutorial/base.html' %}

{% block style %}
<style>
    .card:hover {
        cursor: pointer;
        box-shadow: 0 0 7px #f3f3f3;
    }
</style>
{% endblock style %}

{% block content %}
<div class="collection">
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}

    <div class="d-flex flex-wrap">
        {% for sub_cat in matching_series %}
            <div class="col s12 m6 l4 p-3">
                <div class="card hoverable">
                    <div class="card-body">
                        <h5>{{sub_cat.series_title}}</h5>
                        <p class="p-3">{{sub_cat.series_summary}}</p>
                        <a class='card-link'
                            href="{% url 'tutorial:sub_sub_cat' sub_cat.series_maincategory.category_slug sub_cat.series_slug %}">
                            read more</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    {% endblock content %}

tutorial/templates/tutorial/sub-sub-category.html
{% extends 'tutorial/base.html' %}

{% block style %}
<style>
    .card:hover {
        cursor: pointer;
        box-shadow: 0 0 7px #f3f3f3;
    }
</style>
{% endblock style %}

{% block content %}

<div class="row">
    {% for sub_cat in matching_series %}
    <div class="col-sm-12 col-md-6 col-lg-4 p-3">
        <div class="card hoverable">
            <div class="card-body">
                <h5>{{ sub_cat.tutorial_title }}</h5>
                <p>{{ sub_cat.snippet|safe }}</p>
                <a
                    href="{% url 'tutorial:tutorial_detail' sub_cat.tutorial_series.series_maincategory.category_slug sub_cat.tutorial_series sub_cat.tutorial_slug %}">read
                    more</a>
            </div>

        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}

<!-- 
    sub_cat.tutorial_series.series_maincategory.category_slug
    sub_cat.tutorial_series sub_cat.tutorial_slug
-->

tutorial/templates/tutorial/sub-sub-sub-cat.html
{% extends 'tutorial/base.html' %}

{% block style %}
<style>
    .card:hover {
        cursor: pointer;
        box-shadow: 0 0 7px #f3f3f3;
    }
</style>
{% endblock style %}

{% block content %}

<div class="d-flex flex-wrap">
    {% for sub_cat in matching_series %}

    <div class="col s12 m6 l4 p-3">

        <div class="card hoverable">
            <div class="card-body">
                <h5>{{ sub_cat.section_title }}</h5>
                <p>{{ sub_cat.snippet|safe }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}

tutorial/templates/tutorial/tutorial-detail.html
{% extends 'tutorial/base.html' %}

{% block content %}

<div class="card">
    <div class="card-body">
        <h2 class="card-title">{{ obj.tutorial_title }}</h2>
        <p class="text-muted">{{ obj.date_published }}</p>
        <span class="card-text">{{ obj.tutorial_content | safe}}

    </div>
</div>

{% endblock content %}

users/templates/users/logout.html
{% extends 'tutorial/base.html' %}
{% load crispy_forms_tags %}
{% block style %}
{% endblock style %}

{% block content %}

<p> Thanks for spending quality time with us!</p>

{% endblock content %}

users/templates/users/signin.html
{% extends 'tutorial/base.html' %}
{% load crispy_forms_tags %}
{% block style %}
<style>
    ul {
        list-style-type: none;
    }
</style>
{% endblock style %}

{% block content %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}">
    {{ message }}
</div>
{% endfor %}
{% endif %}
<form action="." method="POST" style="margin:auto; width:70%;">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn waves-effect waves-light" type="submit" name="action">Signin
    </button>
</form>
{% endblock content %}
<!DOCTYPE html>

users/templates/users/signup.html
{% extends 'tutorial/base.html' %}
{% load crispy_forms_tags %}
{% block style %}
<style>
    ul {
        list-style-type: none;
    }
</style>
{% endblock style %}

{% block content %}
<form action="." method="POST" style="margin:auto; width:70%;">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn waves-effect waves-light" type="submit" name="action">Sign Up
    </button>
</form>
{% endblock content %}
<!DOCTYPE html>